# moonraker.conf

[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /opt/printer_data/run/klipper.sock
max_upload_size: 1024

[authorization]
cors_domains:
  *
trusted_clients:
  127.0.0.1
  192.168.0.0/16
  10.0.0.0/8
  172.16.0.0/12

[machine]
provider: none

[octoprint_compat]

[webcam printer1]
service: webrtc-go2rtc
target_fps: 30
target_fps_idle: 5
stream_url: http://mini1:1984/stream.html?src=printer&mode=webrtc
snapshot_url: http://mini1:1984/api/frame.jpeg?src=printer
aspect_ratio: 16:9

[history]

[file_manager]
enable_object_processing: True

[power 3d_printer]
type: homeassistant
address: homeassistant.esstec.ca
port: 443
protocol: https
device: switch.3d_printer_power_switch
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI3Njk2Y2Y0YjJkYzU0OTRhOTE5MGU5YmYwNzgxNjRlOCIsImlhdCI6MTc3NTI1ODUyOSwiZXhwIjoyMDkwNjE4NTI5fQ.-wy8sw5-VO-PEPrgdIKF4lIrloMO1MIf8tz6OygQK0o

[timelapse]
enabled: False
output_path: /opt/printer_data/timelapse/
frame_path: /tmp/timelapse/
ffmpeg_binary_path: /usr/bin/ffmpeg
snapshoturl: http://mini1:1984/api/frame.jpeg?src=printer
